Pedidos.Web.Core/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pedidos.Web.Core.Models;
using Pedidos.Web.Core.Models.Dto;
using System.Diagnostics;
using System.Text;
using X.PagedList;
using static NuGet.Packaging.PackagingConstants;

namespace Pedidos.Web.Core.Controllers
{
    public class PedidosController : Controller
    {
        private readonly ILogger<PedidosController> _logger;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IConfiguration _configuration;

        public PedidosController(ILogger<PedidosController> logger, IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _logger = logger;
            _clientFactory = httpClientFactory;
            _configuration = configuration;

        }

        public async Task<IActionResult> Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10; 

            List<GetPedidosDTO>? model = await GetPedidos();

            IPagedList<GetPedidosDTO> pagedList = model.ToPagedList(pageNumber, pageSize);

            return View(pagedList);
        }

        [HttpGet]
        public async Task<List<GetPedidosDTO>?> GetPedidos()
        {
            try
            {
                var model = new List<GetPedidosDTO>();
                var url = $"GetPedidos";

                using (var client = _clientFactory.CreateClient("ApiPedidos"))
                {
                    var response = await client.GetAsync(url);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<GetPedidosDTO>>(content);
                        return model;
                    }
                }
            }
            catch (System.Exception)
            {

            }
            return null;
        }

        [HttpPost]
        public async Task<IActionResult?> PostPedidos([FromForm] PedidoDTO filters)
        {
            try
            {
                var json = JsonConvert.SerializeObject(filters);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var model = new List<PedidoDTO>();
                var url = $"GuardarPedido";

                using (var client = _clientFactory.CreateClient("ApiPedidos"))
                {
                    var response = await client.PostAsync(url, data);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<PedidoDTO>>(content);
                        return View("Index",model);
                    }
                }
            }
            catch (System.Exception)
            {

            }
            return null;
        }

        [HttpGet]
        public IActionResult AgregarRegistro()
        {
            return PartialView("_AgregarRegistro"); 
        }

        [HttpPost]
        public async Task<IActionResult?> AgregarRegistro(PedidoDTO filters)
        {
            try
            {
                var json = JsonConvert.SerializeObject(filters);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var model = new List<PedidoDTO>();
                var url = $"GuardarPedido";

                using (var client = _clientFactory.CreateClient("ApiPedidos"))
                {
                    var response = await client.PostAsync(url, data);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<PedidoDTO>>(content);
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (System.Exception)
            {

            }
            return null;

            
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pedidos.Web.Core/Controllers/VentasController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pedidos.Web.Core.Models;
using Pedidos.Web.Core.Models.Dto;
using System.Diagnostics;
using System.Text;

namespace Pedidos.Web.Core.Controllers
{
    public class VentasController : Controller
    {
        private readonly ILogger<VentasController> _logger;
        private readonly IHttpClientFactory _clientFactory;
        private readonly IConfiguration _configuration;

        public VentasController(ILogger<VentasController> logger, IHttpClientFactory httpClientFactory, IConfiguration configuration)
        {
            _logger = logger;
            _clientFactory = httpClientFactory;
            _configuration = configuration;

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Comisiones()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult?> GetVentas([FromForm] GetVentasRequestDTO filters)
        {
            try
            {
                var json = JsonConvert.SerializeObject(filters);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var model = new List<VentasAcumuladasDTO>();
                var url = $"GetVentasAcumuladasByPeriodo";

                using (var client = _clientFactory.CreateClient("ApiPedidos"))
                {
                    var response = await client.PostAsync(url, data);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<VentasAcumuladasDTO>>(content);
                        return View("Index",model);
                    }
                }
            }
            catch (System.Exception)
            {

            }
            return null;
        }

        [HttpPost]
        public async Task<IActionResult?> GetComisiones([FromForm] GetComisionesRequestDTO filters)
        {
            try
            {
                var json = JsonConvert.SerializeObject(filters);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var model = new List<ComisionVendedorDTO>();
                var url = $"GetComisionVendedorByPeriodo";

                using (var client = _clientFactory.CreateClient("ApiPedidos"))
                {
                    var response = await client.PostAsync(url, data);
                    if (response.IsSuccessStatusCode)
                    {
                        var content = await response.Content.ReadAsStringAsync();
                        model = JsonConvert.DeserializeObject<List<ComisionVendedorDTO>>(content);
                        return View("Comisiones", model);
                    }
                }
            }
            catch (System.Exception)
            {

            }
            return null;
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Pedidos.Web.Core/Views/Shared/_AgregarRegistro.cshtml
<div class="modal fade" id="agregarPedidoModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Pedido</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="pedidoForm">

                    <div class="row">
                        <div class="col-md-3">
                            <label for="numPedido" class="form-label">Número de Pedido</label>
                            <input type="text" class="form-control" id="numPedido" name="NumPedido">
                        </div>
                        <div class="col-md-3">
                            <label for="cliente" class="form-label">Cliente</label>
                            <input type="text" class="form-control" id="cliente" name="Cliente">
                        </div>
                        <div class="col-md-3">
                            <label for="fecha" class="form-label">Fecha</label>
                            <input type="date" class="form-control" id="fecha" name="Fecha">
                        </div>
                        <div class="col-md-3">
                            <label for="vendedor" class="form-label">Vendedor</label>
                            <input type="text" class="form-control" id="vendedor" name="Vendedor">
                        </div>
                    </div>
                                        

                    <h5>Detalle del Pedido</h5>
                    <div id="itemsContainer">
                        <!-- Tabla para mostrar el detalle -->
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Producto</th>
                                    <th>Precio</th>
                                    <th>Cantidad</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Aquí se agregarán las filas de detalle dinámicamente -->
                            </tbody>
                        </table>
                    </div>

                    <button type="button" class="boton-primario" id="agregarPedido" data-bs-toggle="modal" data-bs-target="#agregarDetalleModal" data-num-pedido="" onclick="abrirAgregarDetalleModal(this)">Agregar Item</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="boton-terciario" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="boton-primario" id="guardarPedido">Guardar</button>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="agregarDetalleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregar Detalle</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="pedidoForm">

                    <div class="row">
                        <div class="col-md-3">
                            <label for="numPedidoDetalle" class="form-label">Número de Pedido</label>
                            <input type="text" class="form-control" id="numPedidoDetalle" name="NumPedido" readonly>
                        </div>
                        <div class="col-md-3">
                            <label for="producto" class="form-label">Producto</label>
                            <input type="text" class="form-control" id="producto" name="Producto">
                        </div>
                        <div class="col-md-3">
                            <label for="precio" class="form-label">Precio</label>
                            <input type="text" class="form-control" id="precio" name="Precio">
                        </div>
                        <div class="col-md-3">
                            <label for="cantidad" class="form-label">Cantidad</label>
                            <input type="text" class="form-control" id="cantidad" name="Cantidad">
                        </div>
                    </div>

                    <button type="button" class="boton-primario" id="agregarItem">Agregar Item</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="boton-terciario" data-bs-dismiss="modal">Cerrar</button>
                
            </div>
        </div>
    </div>
</div>

<script>

    $("#agregarItem").click(function () {
    var numPedido = "123"; 

        $("#agregarItem").attr("data-num-pedido", numPedido);

    $("#agregarDetalleModal").modal("show");
    });
    
    function abrirAgregarDetalleModal(boton) {
        const numPedido = $(boton).data("data-num-pedido");
        console.log("Número de Pedido:", numPedido);
        $("#numPedidoDetalle").val(numPedido);
    }



    $("#guardarDetalle").click(function () {
    const numPedido = $("#numPedidoDetalle").val();
    const producto = $("#producto").val();
    const precio = $("#precio").val();
    const cantidad = $("#cantidad").val();
    const subtotal = $("#subtotal").val();

    
    const detalle = {
        NumPedido: numPedido,
        Producto: producto,
        Precio: precio,
        Cantidad: cantidad,
        Subtotal: subtotal
    };

    // Agrega el detalle al pedido correspondiente en memoria (encuentra el pedido por su número)
    // ...

    // Limpia el formulario
    // ...

    // Cierra el modal "agregarDetalleModal"

    $("#agregarDetalleModal").modal("hide");
});


</script>

Pedidos.Web.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consulta</title>
    <link rel="stylesheet" href="https://use.typekit.net/iua0dbj.css" />
    <link rel="stylesheet" href="~/css/estilo.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/inputs.css" asp-append-version="true" />
    <link href="~/css/spinkit/spinkit.min.css" rel="stylesheet" />
    <link href="~/css/toast/toast.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
    <div class="admin-layout">
        <nav>
            <div class="header-lista">
                @*<img src="~/assets/logo.png" width="150" height="30" />*@
                <div class="separador"></div>
                <div>
                    <ul class="menu_principal">
                        <li>
                            <a class="header-link" asp-area="" asp-controller="Ventas" asp-action="Index">
                                <span>
                                    Ventas Departamentos
                                </span>
                            </a>
                        </li>
                         <li>
                            <a class="header-link" asp-area="" asp-controller="Ventas" asp-action="Comisiones">
                                <span>
                                    Comisiones Vendedores
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="header-link" asp-area="" asp-controller="Pedidos" asp-action="Index">
                                <span>
                                    Pedidos
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="main">
            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>